#!/bin/python

#Solution to Project Euler - problem 10
#Leigh Hall / 31-may-14

#The sum of primes below 10 is 2 + 3 + 5 + 7 = 17
#Find the sum of the primes below 2million

#given enough time this will brute force the solution...

import math

def isprime(n):
	if n==1:
		print "    exiting at n==1"
		return 0
	if n==2:
		print "    exiting at n==2"
		return 1

	max = int(math.ceil(math.sqrt(n)))+1

	if n%2==0:
		print "    exiting at n%2"
		return 0

	for i in range (3, max, 2):
		print "    starting loop"
		print "    ...",i,"(", max,")"
		if n % i == 0:
			print "    exiting following mod test"
			return 0
	
	print "    exiting after exhaustion" #i.e., it's prime...
	return 1

def problem10(n):
	sum=0
	for i in range (2,n ):
		print i
		if isprime(i):
			print "            *****IS PRIME***** ", i
			sum=sum+i
	return sum

print problem10(2000000)
#print problem10(10)
	
